name: CI/CD Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: Rambo@123
          MYSQL_DATABASE: project_db
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Wait for MySQL to be ready
      run: sleep 30

    - name: Run SQL Scripts
      run: |
        mysql -h 127.0.0.1 -u root -pRambo@123 < sql/01_create_climate_table.sql
        mysql -h 127.0.0.1 -u root -pRambo@123 < sql/02_add_humidity_column.sql
        mysql -h 127.0.0.1 -u root -pRambo@123 < sql/03_seed_data.sql

    - name: Install Python & Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install mysql-connector-python

    - name: Run Python Queries
      run: python3 scripts/multi_thread_queries.py
